### ISSUE TITLE
Providing disks as in example in pv.py does not work

### ISSUE THREAD

**Issue by ShyamsundarR** [gluster/gdeploy#384]
In https://github.com/gluster/gdeploy/blob/master/modules/pv.py#L54 the example asks the play to provide a list of disks as disks='["/dev/sdb", "/dev/sdc"]' which if done fails as follows.

### Playbook is (pvc.yml)
    ---
    - hosts: myhostname
      tasks:
      - name: Create PVs
        pv: action=create disks='["/dev/sdb", "/dev/sdc"]' options="--dataalignment 1280k"

### Output of run
$ ansible-playbook -i ./myinventory.ini ./pvc.yml --module-path=<path_to>/gdeploy/modules/

PLAY [myhostname] *********************************

TASK [setup] *******************************************************************
ok: [myhostname]

TASK [Create PVs] **************************************************************
fatal: [myhostname]: FAILED! => {"changed": false, "failed": true, "msg": "  Device [/dev/sdb, not found (or ignored by filtering).\n  Device /dev/sdc] not found (or ignored by filtering).\n", "rc": 5}
        to retry, use: --limit @<blah!>/pvc.retry

PLAY RECAP *********************************************************************
myhostname : ok=1    changed=0    unreachable=0    failed=1

### Issue
The provided disks are being parsed as "[/dev/sdb" and "/dev/sdc]" which results in the said problem IMO.

### Questions
- Should the example change to take one disk at a time (as if I change this to a single disk, the play works)
- OR, Is this a problem that needs a fix?

**Comment by sac** [comment]
Shyam, sorry about that. That is an outdated comment. Should have changed when we changed the behavior.

Your playbook should now look like:

```
---
- hosts: myhostname
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create PVs
    pv: action=create disks="{{ item }}" options="--dataalignment 1280k"
    with_items:
    - /dev/vdc
    - /dev/vdd


```

Earlier we were using python's literal_eval() changed that later on but the comment stayed there.
Commit: https://github.com/gluster/gdeploy/commit/dcc812438064 fixes the issue.
